const state=JSON.parse(localStorage.getItem("spanishSprint")||'{"xp":0,"lessons":0,"correct":0,"answered":0,"cards":0,"streak":0,"lastDay":""}');
const save=()=>{localStorage.setItem("spanishSprint",JSON.stringify(state));render()};
const today=()=>new Date().toISOString().slice(0,10);
function touchStreak(){const d=today();if(state.lastDay!==d){if(state.lastDay){const diff=Math.round((new Date(d)-new Date(state.lastDay))/86400000);state.streak=diff===1?state.streak+1:1}else state.streak=1;state.lastDay=d}}
function addXP(n){touchStreak();state.xp+=n;save()}
function render(){document.querySelector("#xp").textContent=state.xp;document.querySelector("#lessons").textContent=state.lessons;document.querySelector("#cards").textContent=state.cards;document.querySelector("#streak").textContent=state.streak;document.querySelector("#accuracy").textContent=(state.answered?Math.round(state.correct/state.answered*100):0)+"%";const level=Math.floor(state.xp/100)+1,pct=state.xp%100;document.querySelector("#level").textContent="Level "+level+" · "+(level===1?"Beginner":level<4?"Explorer":"Conversationalist");document.querySelector("#progressFill").style.width=pct+"%";document.querySelector("#progressText").textContent=pct+" / 100 XP"}
const modal=document.querySelector("#modal"),content=document.querySelector("#modalContent");function open(html){content.innerHTML=html;modal.classList.remove("hidden")}
document.querySelector("#close").onclick=()=>modal.classList.add("hidden");modal.onclick=e=>{if(e.target===modal)modal.classList.add("hidden")};
const lessons=[["Greetings","Hola = Hello","Buenos días = Good morning","¿Qué tal? = How's it going?","Hasta luego = See you later"],["Useful verbs","ser = to be (identity)","estar = to be (state/location)","tener = to have","querer = to want"],["Everyday phrases","Por favor = Please","Gracias = Thank you","No entiendo = I don't understand","¿Cuánto cuesta? = How much does it cost?"]];
function lesson(){let html='<p class="eyebrow">Mini lesson</p><h2>Spanish essentials</h2><p class="sub">Learn four useful expressions, then mark the lesson complete.</p>';lessons[0].slice(1).forEach(x=>{const p=x.split(" = ");html+='<div class="lesson"><b>'+p[0]+'</b><span>'+p[1]+'</span></div>'});html+='<button class="primary" id="complete">Complete lesson · +25 XP</button>';open(html);document.querySelector("#complete").onclick=()=>{state.lessons++;addXP(25);modal.classList.add("hidden")}}
const cards=[["hola","hello"],["gracias","thank you"],["mañana","tomorrow"],["comida","food"],["amigo","friend"],["casa","house"],["agua","water"],["viaje","trip"]];let cardIndex=0,flipped=false;
function cardsView(){const c=cards[cardIndex];flipped=false;open('<p class="eyebrow">Flashcards</p><h2>Vocabulary sprint</h2><p class="sub">Try to remember the translation before revealing it.</p><div class="flashcard" id="fc"><div><div class="word">'+c[0]+'</div><div class="translation" id="tr">Tap to reveal</div></div></div><div class="actions"><button id="skip">I knew it</button><button class="primary2" id="reveal">Reveal</button></div>');document.querySelector("#fc").onclick=flip;document.querySelector("#reveal").onclick=flip;document.querySelector("#skip").onclick=()=>{state.cards++;addXP(5);cardIndex=(cardIndex+1)%cards.length;cardsView()};function flip(){if(!flipped){flipped=true;document.querySelector("#tr").textContent=c[1]}}}
const questions=[["¿Cómo se dice “thank you”?",["Hola","Gracias","Adiós"],1],["“Casa” means…",["House","Food","Friend"],0],["Choose “Good morning”.",["Buenas noches","Buenos días","Hasta luego"],1],["“Quiero agua” means…",["I have water","I want water","Where is water?"],1]];let qi=0;
function quiz(){qi=0;quizQuestion();function quizQuestion(){if(qi>=questions.length){open('<p class="eyebrow">Quiz complete</p><h2>¡Muy bien!</h2><div class="result"><b>'+state.correct+'/'+state.answered+' overall accuracy</b><p>You earned '+questions.length*10+' XP for finishing this quiz.</p></div><button class="primary" id="done">Finish</button>');document.querySelector("#done").onclick=()=>modal.classList.add("hidden");return}const q=questions[qi],opts=q[1],correct=q[2];let html='<p class="eyebrow">Quick quiz · '+(qi+1)+'/'+questions.length+'</p><h2>'+q[0]+'</h2><div class="answer">';opts.forEach((o,i)=>html+='<button data-i="'+i+'">'+o+'</button>');html+='</div>';open(html);document.querySelectorAll(".answer button").forEach(b=>b.onclick=()=>{const i=+b.dataset.i;state.answered++;if(i===correct){state.correct++;b.classList.add("correct");addXP(10)}else{b.classList.add("wrong");document.querySelectorAll(".answer button")[correct].classList.add("correct")}document.querySelectorAll(".answer button").forEach(x=>x.disabled=true);setTimeout(()=>{qi++;quizQuestion()},650)})}}
document.querySelector("#startBtn").onclick=lesson;document.querySelectorAll("[data-open]").forEach(b=>b.onclick=()=>({lesson:lesson,cards:cardsView,quiz:quiz})[b.dataset.open]());render();